### ISSUE TITLE
Lost data after repeated transmission

### ISSUE THREAD

**Issue by JiriBilek** [SensorsIot/NRF24L01-Bi-Directional-Communication#1]
Hi, thanks for the example, I found it quite useful as a communication cornerstone for my project.

On ideal conditions, the example is running fine. However, when the quality of signal is poor and the devices need to retransmit _the acknowledge message_, an issue comes.
Let's assume the transmitter had sent a data and did not receive the ACK. It retransmits the message up to 15 times. But at the very moment the receiver is yet switched to the transmission phase (because it got data and sent ACK) and sends the acknowledge. Then the both parties are transmitting and nobody can read the message going back.

I fixed it by adding a delay and a loop after successful receiving a message (before `radio.stopListening()`). In a timed loop I waited for any retransmit (and threw away the data as I already got it) in order just for sending ACK to the transmitter. I start sending the message back after this delay that ensures that the other party is finished with the transmission (either successfully or not) and is listening.
I hope my explanation is not too complex.

The code given here, of course, is only a simple example code and I am posting this issue as a help for anyone who would use it to be aware of possible problems.

**Comment by SensorsIot** [comment]
If you provide a pull request or show your changes here I will integrate it into the example.
